# Generated by Django 4.2.29 on 2026-04-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tapasapp', '0002_account_alter_dish_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
